"""create service order history table

Revision ID: 45e9d37ec4e8
Revises: 822063bba049
Create Date: 2026-05-21 20:06:35.334864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45e9d37ec4e8'
down_revision: Union[str, Sequence[str], None] = '822063bba049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_order_histories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.Enum('OPEN', 'IN_PROGRESS', 'WAITING', 'DONE', 'CANCELED', name='serviceorderstatus'), nullable=False),
    sa.Column('new_status', sa.Enum('OPEN', 'IN_PROGRESS', 'WAITING', 'DONE', 'CANCELED', name='serviceorderstatus'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['service_order_id'], ['service_orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_order_histories_id'), 'service_order_histories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_order_histories_id'), table_name='service_order_histories')
    op.drop_table('service_order_histories')
    # ### end Alembic commands ###
