"""update client phone length

Revision ID: 57b18106df33
Revises: c8b9b886ebe3
Create Date: 2026-05-21 12:39:07.207414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57b18106df33'
down_revision: Union[str, Sequence[str], None] = 'c8b9b886ebe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("clients") as batch_op:
        batch_op.alter_column('phone',
          existing_type=sa.VARCHAR(length=20),
          type_=sa.String(length=50),
          existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("clients") as batch_op:
        batch_op.alter_column('phone',
          existing_type=sa.String(length=50),
          type_=sa.VARCHAR(length=20),
          existing_nullable=True)
    # ### end Alembic commands ###
